### ISSUE TITLE
got 'finish' event before all pending jobs done

### ISSUE THREAD

**Issue by jacobbubu** [almost/through2-concurrent#7]
When use it to implement a writeable stream, the 'finish' event fired before all of the pending jobs done.

**Comment by almost** [comment]
You're right that it should definitely wait until all transforms are complete before firing 'finish'. I'm trying to figure out a nice way of fixing this at the moment. If you had a test case showing the failure that'd be really helpful, even more so if it was in the form of a failing unit test :)

**Comment by Serpan911** [comment]
I also encountered such a problem. Here are small tests for dimontration:
https://github.com/Serpan911/through2-concurrent/commit/f7b52482dcf2694cce6818fc8d13faf35110f069

**Comment by almost** [comment]
Thanks for this!

**Comment by YounGoat** [comment]
@jacobbubu Maybe it is triggered by duplicated invoking of ``callback``?

**Comment by duanshiqiang** [comment]
This is a really annoying bug, it swallow us a whole afternoon to figure out why some chunk are missing. Hope it can be fixed asap..

**Comment by YounGoat** [comment]
How about trying this package?
https://www.npmjs.com/package/oct <https://www.npmjs.com/package/oct>
youngoat@163.com

**Comment by moander** [comment]
I tried this because I had the same issue using alternative package `parallel-transform`. Is it no real alternative to do get parallel streams?

https://github.com/mafintosh/parallel-transform/issues/4

**Comment by Tapppi** [comment]
@almost This is due to using `_flush` to make sure all processing is done. That is called after the `Writable` side has already closed (and `finish` called). Node 8 added `_final` which is `_flush` but for the writing side, which allows to easily wait for all processing to complete without emitting `finished`.

An example fix is here https://github.com/mafintosh/parallel-transform/pull/6, but that depends on `readable-stream@^2.3.0` as that is the version that added Node 8 support. I think the only sensible way of surely fixing this here is to include `readable-stream@^2.3.0` as a dependency to force `through2` to also use a newer version (should work in any of the myriad dep tree cases?). Another possibility is to set both `_final` and `_flush` to fix it for anyone using non-ancient deps and fall back to the old behaviour otherwise.

Fixing this without `_final` involves monkey-patching `end()`, [at least one dude used to do this before `_final`](https://medium.com/@CWMma/whats-new-for-streams-in-node-8-736d431083df#Final), but at least I don't feel like that :joy:.

**Comment by almost** [comment]
Thanks to @Tapppi for fixing this! Now published to npm as version 2.0.0 (bumped the major version because this changes semantics)
